#!/bin/bash

echo "Compile your project here"
pip install Flask
pip install requests
pip install dnslib
pip install cryptography
pip install PyCryptodome
pip install pycrypto
pip install pyopenssl
pip install tornado
