#!/bin/bash
DIRECTORY=$(dirname "$0")
echo "Changing to ${DIRECTORY}"
cd  "$DIRECTORY" || exit 1

echo "Run your project here."

help() {
cat << EOF
	Positional arg:
	Challenge type (required, {dns01 | http01}) 
	indicates which ACME challenge type the client should perform. Valid options are dns01 and http01 for the dns-01 and http-01 challenges, respectively.
    
	Keyword args:
    --dir DIR_URL (required) 
    DIR_URL is the directory URL of the ACME server that should be used.

	--record IPv4_ADDRESS (required) 
	IPv4_ADDRESS is the IPv4 address which must be returned by your DNS server for all A-record queries.

	--domain DOMAIN (required, multiple) 
	DOMAIN is the domain for which to request the certificate. If multiple --domain flags are present, a single certificate for multiple domains should be requested. Wildcard domains have no special flag and are simply denoted by, e.g., *.example.net.

	--revoke (optional) 
	If present, your application should immediately revoke the certificate after obtaining it. In both cases, your application should start its HTTPS server and set it up to use the newly obtained certificate.
EOF
}

rm -r certs/*
rm -r keys/*

TYPE=$1
DOMAINS=()
counter=0

while [[ $# -gt 0 ]]; do
  case $1 in
    --dir ) DIR_URL=$2; shift 2 ;;
    --record ) IPv4_ADDRESS=$2; shift 2 ;;
    --domain ) DOMAINS+=($2); shift 2 ;;
    --revoke ) REVOKE=true; shift ;;
    * ) 
		if [ $counter == 1 ]; then 
			echo "unexpected argument"
			exit 0
		else
			TYPE=$1
			((counter+=1))
			shift	
		fi
		;;
  esac
done

if [ -z $TYPE ]; then
	echo "missing Challenge type"
	exit 0
else
	if [ $TYPE != "dns01" ] && [ $TYPE != "http01" ]; then
		echo "invalid Challenge type"
		exit 0
	fi
fi
if [ -z $DIR_URL ]; then echo "missing dir URL"; exit 0; fi
if [ -z $IPv4_ADDRESS ]; then echo "missing record"; exit 0; fi
if [ -z $DOMAINS ]; then echo "missing domain"; exit 0; fi
CMD="--cType $TYPE --dir_url $DIR_URL --record $IPv4_ADDRESS --domains ${DOMAINS[@]}"

if [ ! -z $REVOKE ]; then
	echo "immediately revoke the certificate after obtaining it"
	CMD+=" --revoke"
fi

echo $CMD
python3 main.py $CMD

rm -r certs/*
rm -r keys/*
